add doc optionsSelect
tikivn/tiki-miniapp-docs pull request #63
Opened 2021-12-15 12:09 UTC by phamdang2810-tiki

2021-12-16 08:48 UTC, hanhantiki requested changes

2021-12-16 08:48 UTC, hanhantiki commented on docs/api/ui/option-selector/option-selector.md
> +
thiếu cái fail với complete

2021-12-16 09:02 UTC, phamdang2810-tiki commented on docs/api/ui/option-selector/option-selector.md
> +
Đã add thêm fail với complete

2021-12-20 02:54 UTC, hanhantiki approved these changes

2021-12-20 02:54 UTC, hanhantiki approved these changes

2021-12-20 02:55 UTC, hanhantiki approved these changes

2021-12-20 02:55 UTC, merged